### PR TITLE
Export "Blob URL Store" definition

### PR DESCRIPTION
**Pull request by TimothyGu**
This term is used in the [URL Standard](https://url.spec.whatwg.org/#url-parsing).

### CODE REVIEW

**Comment by TimothyGu** [comment]
Marked as non-substantive for IPR from ash-nazg.

**Comment by TimothyGu** [comment]
I marked this as non-substantive, but apologies if this process is usually done by a WG member rather than the PR author like myself.

**Comment by annevk** [comment]
Wow, seems like a major security hole in the tooling. Can you also generate the HTML output? Then I can commit it.

**Comment by TimothyGu** [comment]
@annevk Done.

**Comment by annevk** [comment]
Thanks for doing this by the way. This should be indexed within 24h.

**Comment by tripu** [comment]
@annevk, anyone can *refresh validation* and *mark as non-substantive* any PR that is not accepted yet. eg, the &ldquo;ipr details&rdquo; that are visible on WICG/animation-worklet#44 and WICG/budget-api#12 take you to the corresponding repo-manager page, where any user user can perform those actions. Chairs can still decide whether that makes sense or not, request further IPR commitments, etc.

**Comment by annevk** [comment]
That seems like a very strange model.

**Comment by tripu** [comment]
@annevk: I imagine @darobin adopted the simple/optimistic approach to security, and erred on the side of letting users do sensible things by default, instead of restricting actions too much.

**Comment by annevk** [comment]
There's no security with this model though. You might as well not have the check, since everything depends on the chairs.

**Pull request merged**
