### PR TITLE
Update Typed Array spec URL

### PR DESCRIPTION
**Pull request by goelakash**

### CODE REVIEW

**Comment by annevk** [comment]
The fix here would be to not reference that specification at all anymore, since it's obsolete. File API should probably entirely rely on IDL for this.

**Comment by arunranga** [comment]
What is the normative definition for ArrayBuffer?

**Comment by annevk** [comment]
@arunranga for the purposes of most platform specifications it's IDL (which in turn will defer to JavaScript).

**Comment by domenic** [comment]
This is not fixed and should be reopened.

**Comment by goelakash** [comment]
@domenic I am not sure what to do here, that's why I closed it.

**Comment by domenic** [comment]
Ah yes, a new issue would be good.

**Pull request closed without merging**
