### PR TITLE
chore(.travis): enable auto-publish

### PR DESCRIPTION
**Pull request by marcoscaceres**
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/FileAPI/pull/129.html" title="Last updated on May 23, 2019, 3:05 AM UTC (9966e24)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/FileAPI/129/6ed8504...9966e24.html" title="Last updated on May 23, 2019, 3:05 AM UTC (9966e24)">Diff</a>

### CODE REVIEW

**Comment by marcoscaceres** [comment]
@siusin @deniak, having some problems with this that I can't figure out:
https://labs.w3.org/echidna/api/status?id=431c7058-5045-49d9-bd87-c418ec0eff2d

I think the "this-latest-shortname" might be invalid because BikeShed adds a "-1-" for the "level" (which is required by BikeShed), but I'm not sure. Could you confirm? We can ping Tab if true.

I'm not sure why the copyright is generating issues, however. The generated markup seems fine, unless there is something obvious I'm not seeing.

**Comment by deniak** [comment]
Here are the headers of the documents:
```
This version:
    https://www.w3.org/TR/2019/WD-fileapi-1-20190522/
Latest published version:
    https://www.w3.org/TR/FileAPI/
Editor's Draft:
    https://w3c.github.io/FileAPI/
Previous Versions:
    https://www.w3.org/TR/2017/WD-FileAPI-20171026/
```

The first thing I notice is that it'll be considered as a shortname change and Echidna currently doesn't support that so you would have to send a request to webreq@w3.org for that version at least.
Then, I'm not sure how bikeshed generates the document but the shortnames in the "This version" link and in the "Latest published version" should be the same. So in this case, you should have something like
```
This version:
    https://www.w3.org/TR/2019/WD-fileapi-1-20190522/
Latest published version:
    https://www.w3.org/TR/fileapi-1/
```

Regarding the copyright, the link for MIT, ERCIM and Keio should be under http**s**.

**Comment by marcoscaceres** [comment]
Thanks @deniak! I'll send a fix for those HTTP URLs and figured out how to fix the levels thing.

**Comment by marcoscaceres** [comment]
@mkruisselbrink, just confirming that you are ok with switching off the levels (see above, as I don't think we want to request a new short name). 

I've fixed the https issues over on BikeShed https://github.com/tabatkins/bikeshed/pull/1478

**Comment by mkruisselbrink** [comment]
Yes, thanks. This looks good to me.

**Comment by marcoscaceres** [comment]
Thanks @mkruisselbrink for confirming. Just ironing out last little things.

**Comment by marcoscaceres** [comment]
Blocked on https://github.com/tabatkins/bikeshed/issues/1480

**Comment by marcoscaceres** [comment]
@deniak, final thing is the switching deliverer issue. How do we proceed with that? Anything I can do to help? It’s currently blocking publication of all other specs in the wg.

**Comment by deniak** [comment]
@marcoscaceres unfortunately, [Echidna is not able yet to handle change of deliverer](https://github.com/w3c/echidna/wiki/How-to-use-Echidna#current-limitations) as it requires some IPP changes.
You will need to send a publication request to webreq@w3.org at least for that version. Once it has been published, you will be able to publish the next versions with echidna.

**Comment by siusin** [comment]
@deniak Ok, I'll do that. 

Do we need to republish all the WebPlatform specs under WebApps WG?

**Comment by deniak** [comment]
yeah, Echidna will reject your document if it changes deliverers

**Comment by siusin** [comment]
All right, in that case, I'll send a pubreq that includes all the specs next Monday :)

**Comment by marcoscaceres** [comment]
Filed https://github.com/w3c/webappswg/issues/7 about republishing ... will file bugs for the other specs.

**Pull request merged**
